### PR TITLE
DEPLOY-659: Align pvc system in infra to support custom Storage Classes and AzureFile

### PR DESCRIPTION
**Pull request by sergiuv2020**

### CODE REVIEW

**Comment by jottley** [comment]
@svidrascu Are these filenames/content reversed?
- pvcAzureFile.yaml
- pvcAwsEFS.yaml

**Review by jottley — COMMENTED** [review]
https://github.com/Alfresco/alfresco-infrastructure-deployment/pull/40#issuecomment-461184416

**Comment by sergiuv2020** [comment]
Lol, Yes, thanks.

**Review by jottley — APPROVED** [review]

**Comment by rgauss** [comment]
Minor note, but should the provider-specific files be named `pv-*` instead of `pvc-*` since they no longer contain a PVC?

**Review by rgauss — APPROVED** [review]

**Pull request merged**
