### PR TITLE
DEPLOY-456: Setup the ingress chart as a requirement of the infrastructure chart

### PR DESCRIPTION
**Pull request by sergiuv2020**
Updated readme and requirements.

### CODE REVIEW

**Comment by rgauss** [comment]
I thought we were going to try to pull these through the 1.x branch?  Are these the same commits?

**Comment by sergiuv2020** [comment]
I merged 1.x to this branch first. Then did a few readme modifications and changed the version.

**Review by kconkas — APPROVED** [review]
LGTM

**Review by nicdoye — APPROVED** [review]
lgtm-pineapple-pen

**Pull request merged**
