### PR TITLE
[DEPLOY-673] Stop ActiveMQ running as root

### PR DESCRIPTION
**Pull request by jottley**
-Update ActiveMQ version to 1.1.0.  This will use an image that does not run as root
-Change minor version

### CODE REVIEW

**Comment by rgauss** [comment]
I think we need to release the ActiveMQ helm chart update before this can be merged?

**Comment by jottley** [comment]
@rgauss Chart is now released

**Review by rgauss — APPROVED** [review]

**Comment by rgauss** [comment]
I think we'll also need to merge this commit to the 4.x branch and create a 4.1.0 stable release?

**Comment by jottley** [comment]
Ok. I'll add a PR for this

**Review by cristina-sirbu — APPROVED** [review]

**Pull request merged**
